# Generated by Django 5.2.11 on 2026-02-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0002_zapnode_management_and_project_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("zap_spider_id", models.CharField(blank=True, max_length=64)),
                ("zap_ascan_id", models.CharField(blank=True, max_length=64)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_scan_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_jobs",
                        to="targets.project",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_jobs",
                        to="targets.target",
                    ),
                ),
                (
                    "zap_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_jobs",
                        to="targets.zapnode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RawZapResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_alerts", models.JSONField(blank=True, default=list)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_results",
                        to="targets.scanjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-fetched_at",),
            },
        ),
        migrations.CreateModel(
            name="ScanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("baseline_like", "Baseline-like"),
                            ("full_active", "Full active"),
                            ("api_scan", "API scan"),
                        ],
                        default="baseline_like",
                        max_length=32,
                    ),
                ),
                ("spider_enabled", models.BooleanField(default=True)),
                ("max_duration_minutes", models.PositiveIntegerField(default=30)),
                ("extra_zap_options", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_profiles",
                        to="targets.project",
                    ),
                ),
                (
                    "zap_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_profiles",
                        to="targets.zapnode",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="scanjob",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scan_jobs",
                to="targets.scanprofile",
            ),
        ),
    ]
