# Generated by Django 5.2.11 on 2026-02-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0003_scanjob_rawzapresult_scanprofile_scanjob_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zap_plugin_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("severity", models.CharField(default="Info", max_length=16)),
                ("description", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("reference", models.TextField(blank=True)),
                ("cwe_id", models.CharField(blank=True, max_length=32)),
                ("wasc_id", models.CharField(blank=True, max_length=32)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("instances_count", models.PositiveIntegerField(default=0)),
                (
                    "scan_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="targets.scanjob",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen",),
                "unique_together": {("target", "zap_plugin_id", "title")},
            },
        ),
        migrations.CreateModel(
            name="RiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.DecimalField(decimal_places=2, max_digits=12)),
                ("counts_by_severity", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="targets.project",
                    ),
                ),
                (
                    "scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="targets.scanjob",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FindingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=2048)),
                ("parameter", models.CharField(blank=True, max_length=255)),
                ("evidence", models.TextField(blank=True)),
                ("attack", models.TextField(blank=True)),
                ("other", models.TextField(blank=True)),
                ("method", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="targets.finding",
                    ),
                ),
                (
                    "scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finding_instances",
                        to="targets.scanjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {
                    ("finding", "scan_job", "url", "parameter", "evidence")
                },
            },
        ),
    ]
