# Generated by Django 5.2.11 on 2026-02-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0004_finding_risksnapshot_findinginstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_finding_ids", models.JSONField(blank=True, default=list)),
                ("resolved_finding_ids", models.JSONField(blank=True, default=list)),
                (
                    "risk_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_from",
                        to="targets.scanjob",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_comparisons",
                        to="targets.target",
                    ),
                ),
                (
                    "to_scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_to",
                        to="targets.scanjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("target", "from_scan_job", "to_scan_job")},
            },
        ),
    ]
