# Generated by Django 5.2.11 on 2026-02-24 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0005_scancomparison"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_file", models.FileField(upload_to="reports/html/")),
                ("json_file", models.FileField(upload_to="reports/json/")),
                ("pdf_file", models.FileField(upload_to="reports/pdf/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="targets.scanjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
