# Generated by Django 5.2.11 on 2026-02-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0006_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("url", "URL"),
                            ("app", "Application"),
                        ],
                        default="url",
                        max_length=16,
                    ),
                ),
                ("uri", models.URLField(blank=True)),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("last_scan_status", models.CharField(blank=True, max_length=16)),
                (
                    "current_risk_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "findings_open_count_by_sev",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("page", models.CharField(max_length=64)),
                ("filters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ScanComparisonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finding_fingerprint", models.CharField(max_length=128)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("resolved", "Resolved"),
                            ("changed", "Changed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("change_type", "finding_fingerprint"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="finding",
            name="confidence",
            field=models.CharField(default="Medium", max_length=32),
        ),
        migrations.AddField(
            model_name="finding",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="finding",
            name="raw_result_ref",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="finding",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted_risk", "Accepted risk"),
                    ("false_positive", "False positive"),
                    ("fixed", "Fixed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="rawzapresult",
            name="checksum",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="rawzapresult",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rawzapresult",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rawzapresult",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="risksnapshot",
            name="breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="scan_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_a",
                to="targets.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="scan_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_b",
                to="targets.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="scope",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("target", "Target"),
                    ("asset", "Asset"),
                ],
                default="target",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together={("target", "zap_plugin_id", "title", "fingerprint")},
        ),
        migrations.AddIndex(
            model_name="rawzapresult",
            index=models.Index(
                fields=["scan_job", "-fetched_at"],
                name="targets_raw_scan_jo_11d9a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["project", "target", "-created_at"],
                name="targets_sca_project_1eda3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["status", "-created_at"], name="targets_sca_status_fb8b81_idx"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="targets.target",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="targets.asset",
            ),
        ),
        migrations.AddField(
            model_name="risksnapshot",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_snapshots",
                to="targets.asset",
            ),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_comparisons",
                to="targets.asset",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["asset", "-last_seen"], name="targets_fin_asset_i_7b0ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["scan_job"], name="targets_fin_scan_jo_4c9db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["fingerprint"], name="targets_fin_fingerp_7d1370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["severity", "status"], name="targets_fin_severit_807ad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(
                fields=["asset", "-created_at"], name="targets_ris_asset_i_c693d5_idx"
            ),
        ),
        migrations.AddField(
            model_name="savedview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scancomparisonitem",
            name="comparison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="targets.scancomparison",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["target", "name"], name="targets_ass_target__fda146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["last_scanned_at"], name="targets_ass_last_sc_024673_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("target", "name", "asset_type")},
        ),
        migrations.AlterUniqueTogether(
            name="savedview",
            unique_together={("user", "name", "page")},
        ),
        migrations.AddIndex(
            model_name="scancomparisonitem",
            index=models.Index(
                fields=["comparison", "change_type"],
                name="targets_sca_compari_e74ded_idx",
            ),
        ),
    ]
