# Generated by Django 5.2.11 on 2026-02-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0007_asset_savedview_scancomparisonitem_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together={("scan_job", "fingerprint")},
        ),
    ]
