# Generated by Django 5.2.11 on 2026-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0007_asset_savedview_scancomparisonitem_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(
                fields=('scan_job', 'fingerprint'),
                condition=models.Q(scan_job__isnull=False) & ~models.Q(fingerprint=''),
                name='targets_finding_scan_job_fingerprint_nonempty_uniq',
            ),
        ),
    ]
