# Generated by Django 5.2.11 on 2026-02-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0008_alter_finding_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("spider_progress", models.PositiveSmallIntegerField(default=0)),
                ("ascan_progress", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="finding",
            name="targets_finding_scan_job_fingerprint_nonempty_uniq",
        ),
        migrations.AddField(
            model_name="scanjob",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="last_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="node_strategy",
            field=models.CharField(
                choices=[("auto", "Auto"), ("pinned", "Pinned")],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="schedule_interval_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="schedule_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("interval", "Interval"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="schedule_weekday",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanprofile",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanprofile",
            name="zap_policy_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="target",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="target",
            name="exclude_regex",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="target",
            name="include_regex",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("healthy", "Healthy"),
                    ("unreachable", "Unreachable"),
                    ("disabled", "Disabled"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="max_concurrent",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="rawzapresult",
            name="scan_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_results",
                to="targets.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="scan_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="targets.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="zap_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="targets.zapnode",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="targets.scanrun",
            ),
        ),
        migrations.AddField(
            model_name="findinginstance",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finding_instances",
                to="targets.scanrun",
            ),
        ),
        migrations.AddField(
            model_name="rawzapresult",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_results",
                to="targets.scanrun",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="targets.scanrun",
            ),
        ),
        migrations.AddField(
            model_name="risksnapshot",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_snapshots",
                to="targets.scanrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("fingerprint", ""), _negated=True),
                    ("scan_job__isnull", False),
                ),
                fields=("scan_job", "fingerprint"),
                name="targets_finding_scan_job_fingerprint_nonempty_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["status", "created_at"], name="targets_sca_status_de9c2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["scan_job", "created_at"], name="targets_sca_scan_jo_6511ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["zap_node", "status"], name="targets_sca_zap_nod_1bb106_idx"
            ),
        ),
    ]
