# Generated by Django 5.2.11 on 2026-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0009_scanrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="findinginstance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="risksnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="savedview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scancomparison",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scanprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="zapnode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="zapnode",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("healthy", "Healthy"),
                    ("unhealthy", "Unhealthy"),
                    ("disabled", "Disabled"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="zapnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("healthy", "Healthy"),
                    ("unhealthy", "Unhealthy"),
                    ("disabled", "Disabled"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
